// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMXh5q2E6njyDIJ_fyp_lCuVTP3QDemiI',
    appId: '1:594373209733:web:e9242bbe88c04a1a70c3ec',
    messagingSenderId: '594373209733',
    projectId: 'better-than-never-tc',
    authDomain: 'better-than-never-tc.firebaseapp.com',
    databaseURL: 'https://better-than-never-tc-default-rtdb.firebaseio.com',
    storageBucket: 'better-than-never-tc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByleusIRG5UjLJS68Y2-wn8prLsTIcQcs',
    appId: '1:594373209733:android:22cbd2281a051cbc70c3ec',
    messagingSenderId: '594373209733',
    projectId: 'better-than-never-tc',
    databaseURL: 'https://better-than-never-tc-default-rtdb.firebaseio.com',
    storageBucket: 'better-than-never-tc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk24JsFCHtdwe8O6zf0aJBl3e5GRkqPOE',
    appId: '1:594373209733:ios:fd5541e24efeb5e370c3ec',
    messagingSenderId: '594373209733',
    projectId: 'better-than-never-tc',
    databaseURL: 'https://better-than-never-tc-default-rtdb.firebaseio.com',
    storageBucket: 'better-than-never-tc.firebasestorage.app',
    iosBundleId: 'com.example.lodzTrashBin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk24JsFCHtdwe8O6zf0aJBl3e5GRkqPOE',
    appId: '1:594373209733:ios:fd5541e24efeb5e370c3ec',
    messagingSenderId: '594373209733',
    projectId: 'better-than-never-tc',
    databaseURL: 'https://better-than-never-tc-default-rtdb.firebaseio.com',
    storageBucket: 'better-than-never-tc.firebasestorage.app',
    iosBundleId: 'com.example.lodzTrashBin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMXh5q2E6njyDIJ_fyp_lCuVTP3QDemiI',
    appId: '1:594373209733:web:3148d302a0e687e670c3ec',
    messagingSenderId: '594373209733',
    projectId: 'better-than-never-tc',
    authDomain: 'better-than-never-tc.firebaseapp.com',
    databaseURL: 'https://better-than-never-tc-default-rtdb.firebaseio.com',
    storageBucket: 'better-than-never-tc.firebasestorage.app',
  );
}
